repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.0  # CURRENT_TAG/COMMIT_HASH
    hooks:
    - id: jupytext
      args: [--from, py, --to, ipynb, --update-metadata, '{"jupytext": {"cell_metadata_filter": "all"}}']
  - repo: local
    hooks:
      - id: nbconvert
        name: nbconvert
        entry: >-
          jupyter nbconvert solution.ipynb
            --TagRemovePreprocesser.enabled=True
            --TagRemovePreprocessor.remove_cell_tags solution
            --to notebook
            --output exercise.ipynb
        pass_filenames: false
        language: system